# Generated by Django 2.2.10 on 2020-07-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_auto_20200714_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responseoption',
            options={'verbose_name': 'Response option', 'verbose_name_plural': 'Response options'},
        ),
        migrations.AlterModelOptions(
            name='surveyresponse',
            options={'verbose_name': 'Survey response', 'verbose_name_plural': 'Survey responses'},
        ),
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.TextField(blank=True, db_index=True),
        ),
    ]
